class Elements:
    ACCESS_CODE_TEXT_BOX = '//input[@id="access-code"]'
    SIGN_IN = '//div[@class="wds-flex wds-items-center wds-justify-center"]'
    SELECT_TITLE = '//div[@class="wds-h-[78%] wds-select-none"]'
    SELECT_DETAILS_SECTION = '//a[@id="detailsSection"]'
    SELECT_VIDEO_SECTION = '//a[@id="videosSection"]'
    PLAY_BUTTON = '//button[@class="icon-width-gen wds-cursor-pointer"]'
    IFRAME_ID = 'video_player'
    CONTINUE_WATCHING = '//button[@class="wds-outline-none"]'
    VIDEO_CONTAINER = '//div[@id="media-player"]'
    VOLUME_CONTROLLER = '//div[@aria-label="Mute button"]'
    SETTINGS = '//div[@aria-label="Settings"]'
    BACK = '(//button[@role="button"])[1]'
    SIGN_OUT = '(//button[@id="signOutSideBar"])'